services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_forecast_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: stock_forecast_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_stock_forecast:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost",
        ]
      interval: 2s
      timeout: 2s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata_stock_forecast:
